In [1]:
import numpy as np 

In [2]:
import cv2

In [3]:
print("Numpy and CV2 packages are imported")

Numpy and CV2 packages are imported


In [4]:
# reading an image
img = cv2.imread('aaa.jpeg',1)

In [5]:
cv2.imshow('image',img)

In [6]:
cv2.waitKey(1000)

-1

In [7]:
# closing the image window
cv2.destroyAllWindows()

In [8]:
# displaying the numpy formation within image
print(img)

[[[213 208 207]
  [220 215 214]
  [221 216 215]
  ...
  [105 140 143]
  [122 153 156]
  [129 158 162]]

 [[210 205 204]
  [216 212 211]
  [219 214 213]
  ...
  [ 96 134 136]
  [114 145 148]
  [119 150 153]]

 [[199 195 194]
  [204 202 201]
  [209 205 204]
  ...
  [ 97 137 136]
  [108 142 142]
  [109 143 143]]

 ...

 [[ 32 119 151]
  [ 44 128 163]
  [ 58 132 174]
  ...
  [ 80  63  60]
  [ 71  56  53]
  [ 26  11   8]]

 [[ 41 142 174]
  [ 49 143 179]
  [ 50 127 173]
  ...
  [ 77  60  57]
  [ 75  60  57]
  [ 27  12   9]]

 [[ 61 170 202]
  [ 55 155 190]
  [ 50 128 175]
  ...
  [ 75  58  55]
  [ 76  61  58]
  [ 38  23  20]]]


In [9]:
# display image information type
print(type(img))

<class 'numpy.ndarray'>


In [10]:
resized = cv2.resize(img,(1024,760))

In [11]:
cv2.imshow("ImageWindow",resized)

In [12]:
cv2.waitKey(1000)

-1

In [13]:
# closing the image window
cv2.destroyAllWindows()

In [14]:
# create a cascade classifier object
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

In [15]:
gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [16]:
# search for the coordinates of the image
faces = face_cascade.detectMultiScale(gray_img,scaleFactor=1.05,minNeighbors=5)

In [17]:
print(type(faces))

<class 'numpy.ndarray'>


In [18]:
print(faces)

[[40 48 76 76]
 [91 50 88 88]]


In [19]:
# adding rectangular facebox
for x,y,w,h in faces:
    img == cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),2)

In [20]:
cv2.imshow("gray",img)

In [21]:
cv2.waitKey(1000)

-1

In [22]:
cv2.destroyAllWindows()